approvals:
  minimum: 2
  pattern: "^(:\\+1:|👍)"
  # note that `from` is by default empty,
  # accepting any matching comment as approval
  from:
    # commenter must be either one of:
    orgs:
      # a public zalando org member
      # (any org in here counts)
      - zalando
    # OR a collaborator of the repo
    collaborators: true
commit:
  message:
    patterns: # commit message has to match any one of
      - ".+" # Any non-empty message

X-Zalando-Team: stups
